[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python trend_scanner.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
memory = "512MB" 